### ISSUE TITLE
swww crashes when display resolution >1080p

### ISSUE THREAD

**Issue by s-daveb** [Horus645/swww#118]
## Problem
I'm not sure when this started happening, but on my Arch linux system, with libmesa-git and a few other custom dependencies installed. I'm getting the following error if I set my display manager resolution higher than 1080p.
`thread 'main' panicked at 'internal error: entered unreachable code: Iterators of zip_eq have different sizes: 8294400, 2073600', /usr/src/debug/swww-git/swww/utils/src/comp_decomp.rs:207:9`

After finagling with the PKGBUILD scripts, I managed to get a debug build with symbols. Here's my system information and a stack trace...

## System Information
```
~ ❯ uname -a
Linux vall 6.3.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000 x86_64 GNU/Linux
~ ❯ pacman -Q | grep hyprland
hyprland 0.25.0-1
xdg-desktop-portal-hyprland-git 1:r282.2bdadd2-1

~ ❯ pacman -Q | grep -e "-git"
directx-headers-git r181.34c9866-1
libpamac-git 1.5.3.r0.g57bef1e-1
mesa-git 23.2.0_devel.170820.cabbbbf0af1.dae32bb875358c786b404388bf1ee875-1
pamac-aur-git 10.5.1.r1.g0c29027-1
sddm-git 0.19.0.218.g58a3517-1
spirv-headers-git 1:1.3.239.0.r9.gaa331ab-1
sunshine-git nightly.dev.r377.g7e8c43c-1
swww-git 0.7.3-1
waybar-git r2527.b0695375-1
wine-git 8.2.r125.g3fb2a5d55e9-1
xdg-desktop-portal-hyprland-git 1:r282.2bdadd2-1
```

### Stacktrace
```
 RUST_BACKTRACE=full WAYLAND_DISPLAY=wayland-1 swww init --no-daemon
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
22:36:22 [INFO] (main) Initialization succeeded! Starting main loop...
thread 'main' panicked at 'internal error: entered unreachable code: Iterators of zip_eq have different sizes: 8294400, 2073600', /usr/src/debug/swww-git/swww/utils/src/comp_decomp.rs:207:9
stack backtrace:
   0:     0x5582d54fc69a - std::backtrace_rs::backtrace::libunwind::trace::h38953cd7b82c38d3
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5582d54fc69a - std::backtrace_rs::backtrace::trace_unsynchronized::h53802a8b087ae509
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5582d54fc69a - std::sys_common::backtrace::_print_fmt::h0806bc2b3dfbb06c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5582d54fc69a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6bd42fa772461846
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5582d551bb1e - core::fmt::write::h086d90dd8e1b1a3f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x5582d54f9d75 - std::io::Write::write_fmt::h18f12173b1839b43
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x5582d54fc465 - std::sys_common::backtrace::_print::hfeb1e373746d03b6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5582d54fc465 - std::sys_common::backtrace::print::h9dc79345d5a578b2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5582d54fdc1f - std::panicking::default_hook::{{closure}}::h45526a9efda640f6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x5582d54fd95b - std::panicking::default_hook::h3e08227c1528c168
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x5582d54fe1c8 - std::panicking::rust_panic_with_hook::he81c02edd7e7b80e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:     0x5582d54fe0c9 - std::panicking::begin_panic_handler::{{closure}}::h98331a6e5528817d
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:     0x5582d54fcb06 - std::sys_common::backtrace::__rust_end_short_backtrace::h83c0d32dd2d13f12
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x5582d54fddd2 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:     0x5582d5453ec3 - core::panicking::panic_fmt::h9ad38cbb8980e66e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:     0x5582d548fb3c - utils::comp_decomp::pack_bytes::h3460629c2afe9fbd
  16:     0x5582d548fb3c - utils::comp_decomp::ReadiedPack::new::h69adf5d051b7cd64
                               at /usr/src/debug/swww-git/swww/utils/src/comp_decomp.rs:170:24
  17:     0x5582d548bbe0 - swww_daemon::processor::Processor::import_cached_img::hafcef29e7a27d5a5
                               at /usr/src/debug/swww-git/swww/daemon/src/processor/mod.rs:182:24
  18:     0x5582d5472fd2 - swww_daemon::main_loop::{{closure}}::hf7677f239533356b
                               at /usr/src/debug/swww-git/swww/daemon/src/main.rs:448:45
  19:     0x5582d5472fd2 - calloop::loop_logic::EventLoop<Data>::run::h68cb94304ba95629
                               at /home/sdavid/.cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5/src/loop_logic.rs:456:13
  20:     0x5582d546d152 - swww_daemon::main_loop::hc5fb23ce70ec28ac
                               at /usr/src/debug/swww-git/swww/daemon/src/main.rs:434:21
  21:     0x5582d546d152 - swww_daemon::main::hbe93e110d3d0ef1e
                               at /usr/src/debug/swww-git/swww/daemon/src/main.rs:248:5
  22:     0x5582d5489296 - core::ops::function::FnOnce::call_once::hefdf8885547ad3a6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
  23:     0x5582d5489296 - std::sys_common::backtrace::__rust_begin_short_backtrace::he6f79c8983b9efd8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:134:18
  24:     0x5582d54848a2 - std::rt::lang_start::{{closure}}::h8b8914f21f74f398
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:166:18
  25:     0x5582d54f5c3c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h814f0ad687ab2f92
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  26:     0x5582d54f5c3c - std::panicking::try::do_call::had9b6a5cabf2fdc8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  27:     0x5582d54f5c3c - std::panicking::try::h5074e9976b13e92c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  28:     0x5582d54f5c3c - std::panic::catch_unwind::he1669253985d4352
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  29:     0x5582d54f5c3c - std::rt::lang_start_internal::{{closure}}::hd778e2099ecb758e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  30:     0x5582d54f5c3c - std::panicking::try::do_call::h1ce263ca927523fa
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  31:     0x5582d54f5c3c - std::panicking::try::he3d901a7a8ca0bfd
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  32:     0x5582d54f5c3c - std::panic::catch_unwind::hb9e5b8ae73c93b8f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  33:     0x5582d54f5c3c - std::rt::lang_start_internal::h2947494479068ade
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  34:     0x5582d546fa2c - main
  35:     0x7fbbdb7fe850 - <unknown>
  36:     0x7fbbdb7fe90a - __libc_start_main
  37:     0x5582d5454455 - _start
  38:                0x0 - <unknown>
```

It's worked just fine at higher resolutions than 1080p in the past, so I'm thinking maybe a dependency could have been updated and an API is no longer behaving as it used to - but that is pure speculation on my part.

**Comment by s-daveb** [comment]
I've removed the Unreachable block on line 207 in comp_decomp.rs, and when I do so, the following log messages appear, my wallpaper loads, but then the daemon crashes immediately:

```
WARNING: socket file /run/user/1000/swww.socket was not deleted when the previous daemon exited
22:45:12 [0m[36m[DEBUG] [0m(main) swww_daemon: Made socket in "/run/user/1000/swww.socket" (pathname) and initialized logger. Starting daemon...
22:45:12 [0m[36m[DEBUG] [0m(main) swww_daemon: New background with output: OutputInfo { id: 49, model: "LG TV", make: "LG Electronics", name: "HDMI-A-1", description: "LG Electronics LG TV 0x01010101 (HDMI-A-1)", location: (0, 0), physical_size: (1600, 900), subpixel: Unknown, transform: Normal, scale_factor: 2, modes: [Mode { dimensions: (3840, 2160), refresh_rate: 60000, is_current: true, is_preferred: false }], obsolete: false }
22:45:12 [0m[34m[INFO] [0m(main) Initialization succeeded! Starting main loop...
22:45:12 [0m[36m[DEBUG] [0m(main) swww_daemon: Clearing output: HDMI-A-1
22:45:12 [0m[36m[DEBUG] [0m(main) swww_daemon: Configured HDMI-A-1: 1920x1080, scale: 1, currently displaying: color: 000
22:45:13 [0m[36m[DEBUG] [0m(main) swww_daemon: Decompressed img.
22:45:13 [0m[36m[DEBUG] [0m(main) swww_daemon: Clearing output: HDMI-A-1
22:45:13 [0m[36m[DEBUG] [0m(main) swww_daemon: Configured HDMI-A-1: 1920x1080, scale: 2, currently displaying: color: 000
```

**Comment by s-daveb** [comment]
Update: I tried the solution from issue #108 in [this comment](https://github.com/Horus645/swww/issues/108#issuecomment-1493399668)

I ran the following, and even in 4K, I can use my wallpapers now. x
```
mv ~/.cache/swww/eDP-1 ~/.cache/swww/eDP-1.save
rm /var/run/user/1000/swww.socket
```

mv ~/.cache/swww/eDP-1 ~/.cache/swww/eDP-1.save
rm /var/run/user/1000/swww.socket
